In [170]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

# 可視化モジュール
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 小数第３まで表示
%precision 3

'%.3f'

In [171]:
wine_df = pd.read_csv("winequality-red.csv",sep=";")
wine_df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [172]:
X=wine_df.loc[:,["fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol"]].values
X

array([[  7.4  ,   0.7  ,   0.   , ...,   3.51 ,   0.56 ,   9.4  ],
       [  7.8  ,   0.88 ,   0.   , ...,   3.2  ,   0.68 ,   9.8  ],
       [  7.8  ,   0.76 ,   0.04 , ...,   3.26 ,   0.65 ,   9.8  ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   3.42 ,   0.75 ,  11.   ],
       [  5.9  ,   0.645,   0.12 , ...,   3.57 ,   0.71 ,  10.2  ],
       [  6.   ,   0.31 ,   0.47 , ...,   3.39 ,   0.66 ,  11.   ]])

In [173]:
y=wine_df.loc[:,["quality"]].values
y

array([[5],
       [5],
       [5],
       ..., 
       [6],
       [5],
       [6]])

In [174]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [175]:
# ランダムフォレストによる学習
from sklearn.ensemble import RandomForestClassifier
rfc_1 = RandomForestClassifier(random_state=0, n_estimators=10)
rfc_1.fit(X_train, y_train)

/Users/yutohagiwara/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [176]:
# 正答率を出力
print('train accuracy: %.3f' % rfc_1.score(X_train, y_train))
print('test  accuracy: %.3f' % rfc_1.score(X_test, y_test))

train accuracy: 0.981
test  accuracy: 0.640


In [177]:
# 特徴量の重要度を出力
importances = rfc_1.feature_importances_
importances

array([ 0.068,  0.097,  0.083,  0.085,  0.065,  0.074,  0.103,  0.09 ,
        0.081,  0.126,  0.127])

In [178]:
X2=wine_df.loc[:,["volatile acidity","citric acid","chlorides","total sulfur dioxide","density","sulphates","alcohol"]].values
X2

array([[  0.7  ,   0.   ,   0.076, ...,   0.998,   0.56 ,   9.4  ],
       [  0.88 ,   0.   ,   0.098, ...,   0.997,   0.68 ,   9.8  ],
       [  0.76 ,   0.04 ,   0.092, ...,   0.997,   0.65 ,   9.8  ],
       ..., 
       [  0.51 ,   0.13 ,   0.076, ...,   0.996,   0.75 ,  11.   ],
       [  0.645,   0.12 ,   0.075, ...,   0.995,   0.71 ,  10.2  ],
       [  0.31 ,   0.47 ,   0.067, ...,   0.995,   0.66 ,  11.   ]])

In [179]:
from sklearn.model_selection import train_test_split
X2_train, X2_test, y_train, y_test = train_test_split(X2, y, test_size = 0.3, random_state = 0)

In [180]:
# ランダムフォレストによる学習
from sklearn.ensemble import RandomForestClassifier
rfc_1 = RandomForestClassifier(random_state=0, n_estimators=10)
rfc_1.fit(X2_train, y_train)

/Users/yutohagiwara/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [181]:
# 正答率を出力
print('train accuracy: %.3f' % rfc_1.score(X2_train, y_train))
print('test  accuracy: %.3f' % rfc_1.score(X2_test, y_test))

train accuracy: 0.979
test  accuracy: 0.690


In [182]:
import numpy as np
import pandas as pd
 
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.externals import joblib 

In [151]:
predict = rfc_1.predict(X2_test)

In [153]:
predict

array([6, 5, 7, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 4, 6, 7, 7, 5, 5, 5, 6, 5, 6,
       6, 6, 5, 5, 7, 5, 6, 5, 5, 6, 5, 7, 7, 5, 6, 6, 5, 5, 6, 6, 7, 6, 5,
       5, 6, 6, 6, 5, 5, 6, 6, 6, 5, 5, 5, 7, 5, 5, 6, 6, 6, 5, 7, 5, 5, 6,
       6, 6, 5, 5, 6, 6, 6, 5, 5, 5, 7, 6, 5, 6, 6, 5, 5, 6, 5, 5, 5, 5, 5,
       6, 5, 7, 6, 6, 5, 6, 5, 7, 7, 6, 7, 5, 5, 5, 5, 6, 5, 6, 5, 7, 5, 5,
       6, 6, 7, 6, 6, 5, 6, 5, 5, 6, 7, 5, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5,
       6, 5, 6, 5, 5, 6, 5, 6, 7, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 5, 6,
       6, 7, 5, 5, 5, 6, 7, 6, 6, 6, 6, 5, 7, 5, 6, 5, 7, 7, 5, 5, 6, 6, 6,
       6, 5, 5, 6, 5, 6, 6, 6, 5, 6, 5, 5, 5, 5, 6, 5, 5, 6, 6, 6, 5, 5, 5,
       7, 6, 6, 6, 6, 5, 6, 5, 5, 5, 7, 6, 5, 5, 5, 6, 6, 5, 6, 6, 6, 6, 6,
       5, 6, 5, 5, 6, 6, 6, 7, 7, 6, 5, 6, 5, 5, 6, 5, 5, 5, 5, 7, 5, 6, 5,
       6, 5, 6, 5, 5, 5, 7, 6, 6, 6, 6, 5, 5, 5, 5, 6, 7, 5, 6, 5, 6, 6, 6,
       6, 6, 6, 7, 5, 7, 6, 6, 6, 5, 5, 5, 7, 5, 5, 5, 6, 6, 5, 6, 6, 5, 6,
       5, 6,

### 課題

In [159]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

# 可視化モジュール
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 小数第３まで表示
%precision 3

'%.3f'

In [160]:
wine = pd.read_csv("train.csv")
wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [165]:
X1=wine_df.loc[:,["volatile acidity","citric acid","chlorides","total sulfur dioxide","density","sulphates","alcohol"]].values
X1

array([[  0.7  ,   0.   ,   0.076, ...,   0.998,   0.56 ,   9.4  ],
       [  0.88 ,   0.   ,   0.098, ...,   0.997,   0.68 ,   9.8  ],
       [  0.76 ,   0.04 ,   0.092, ...,   0.997,   0.65 ,   9.8  ],
       ..., 
       [  0.51 ,   0.13 ,   0.076, ...,   0.996,   0.75 ,  11.   ],
       [  0.645,   0.12 ,   0.075, ...,   0.995,   0.71 ,  10.2  ],
       [  0.31 ,   0.47 ,   0.067, ...,   0.995,   0.66 ,  11.   ]])

In [166]:
y=wine.loc[:,["quality"]].values
y

array([[5],
       [5],
       [5],
       ..., 
       [6],
       [6],
       [6]])

In [169]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size = 0.3, random_state = 0)
y_train=np.reshape(y_train,(-1))
y_test=np.reshape(y_test,(-1))

ValueError: Found input variables with inconsistent numbers of samples: [1599, 1119]

In [164]:
# ランダムフォレストによる学習
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0, n_estimators=10)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [154]:
# データの分割方法を指定
from sklearn.model_selection import KFold
kf = KFold(n_splits=10, shuffle=True, random_state=0)

In [156]:
# 交差検証を実行
# (モデル, 説明変数, 目的変数, 分割の方法)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(rfc, X_train, y_train, cv=kf)
scores

array([ 0.703,  0.617,  0.648,  0.648,  0.703,  0.648,  0.664,  0.656,
        0.695,  0.669])