In [39]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# 小数第３まで表示
%precision 3

'%.3f'

In [40]:
wine_df= pd.read_csv("train.csv")
wine_df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [41]:
X=wine_df.loc[:,["volatile acidity","citric acid","chlorides","total sulfur dioxide","density","sulphates","alcohol"]].values
X

array([[  0.7  ,   0.   ,   0.076, ...,   0.998,   0.56 ,   9.4  ],
       [  0.88 ,   0.   ,   0.098, ...,   0.997,   0.68 ,   9.8  ],
       [  0.76 ,   0.04 ,   0.092, ...,   0.997,   0.65 ,   9.8  ],
       ..., 
       [  0.69 ,   0.07 ,   0.091, ...,   0.996,   0.6  ,  11.3  ],
       [  0.69 ,   0.07 ,   0.091, ...,   0.996,   0.6  ,  11.3  ],
       [  0.39 ,   0.12 ,   0.065, ...,   0.993,   0.53 ,  13.3  ]])

In [42]:
y=wine_df.loc[:,["quality"]].values
y

array([[5],
       [5],
       [5],
       ..., 
       [6],
       [6],
       [6]])

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)
y_train=np.reshape(y_train,(-1))
y_test=np.reshape(y_test,(-1))

In [87]:
# ランダムフォレストによる学習
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0, n_estimators=10)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [88]:
# データの分割方法を指定
from sklearn.model_selection import KFold
kf = KFold(n_splits=10, shuffle=True, random_state=0)

In [89]:
# 交差検証を実行
# (モデル, 説明変数, 目的変数, 分割の方法)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(rfc, X_train, y_train, cv=kf)
scores

array([ 0.608,  0.722,  0.684,  0.654,  0.667,  0.654,  0.59 ,  0.615,
        0.744,  0.615])

In [90]:
# 正答率を出力
print('train accuracy: %.3f' % rfc.score(X_train, y_train))
print('test  accuracy: %.3f' % rfc.score(X_test, y_test))

train accuracy: 0.982
test  accuracy: 0.670


In [91]:
# 特徴量の重要度を出力
importances = rfc.feature_importances_
importances

array([ 0.139,  0.112,  0.126,  0.151,  0.116,  0.137,  0.219])

In [92]:
from sklearn.model_selection import GridSearchCV

In [103]:
parameters = {
    'n_estimators'      : [5, 10, 30,50],
    'max_features'      : [3,4,5,6,7],
    'random_state'      : [0],
    'min_samples_split' : [3, 5, 10, 20],
    'max_depth'         : [3, 5, 10,12,15]
}

In [104]:
classifier = GridSearchCV(RandomForestClassifier(), parameters)
classifier.fit(X_train, y_train)
print(classifier.best_estimator_)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features=6, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=5,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)


In [109]:
# ランダムフォレストによる学習
from sklearn.ensemble import RandomForestClassifier
rfc_1 = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features=6, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=5,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)
rfc_1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features=6, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=5,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [110]:
# 正答率を出力
print('train accuracy: %.3f' % rfc_1.score(X_train, y_train))
print('test  accuracy: %.3f' % rfc_1.score(X_test, y_test))

train accuracy: 0.936
test  accuracy: 0.616


In [111]:
X0=wine_df.loc[:,["fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol"]].values
X0

array([[  7.4 ,   0.7 ,   0.  , ...,   3.51,   0.56,   9.4 ],
       [  7.8 ,   0.88,   0.  , ...,   3.2 ,   0.68,   9.8 ],
       [  7.8 ,   0.76,   0.04, ...,   3.26,   0.65,   9.8 ],
       ..., 
       [  7.  ,   0.69,   0.07, ...,   3.38,   0.6 ,  11.3 ],
       [  7.  ,   0.69,   0.07, ...,   3.38,   0.6 ,  11.3 ],
       [  7.1 ,   0.39,   0.12, ...,   3.3 ,   0.53,  13.3 ]])

In [112]:
X0_train, X0_test, y0_train, y0_test = train_test_split(X0, y, test_size = 0.3, random_state = 1)
y0_train=np.reshape(y_train,(-1))
y0_test=np.reshape(y_test,(-1))

In [113]:
classifier = GridSearchCV(RandomForestClassifier(), parameters)
classifier.fit(X0_train, y0_train)
print(classifier.best_estimator_)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features=4, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=3,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)


In [114]:
# ランダムフォレストによる学習
from sklearn.ensemble import RandomForestClassifier
rfc_2 = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features=4, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=3,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)
rfc_2.fit(X0_train, y0_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features=4, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=3,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [115]:
# 正答率を出力
print('train accuracy: %.3f' % rfc_2.score(X0_train, y0_train))
print('test  accuracy: %.3f' % rfc_2.score(X0_test, y0_test))

train accuracy: 0.977
test  accuracy: 0.643


In [116]:
# 特徴量の重要度を出力
importances = rfc_2.feature_importances_
importances

array([ 0.073,  0.089,  0.061,  0.067,  0.089,  0.065,  0.106,  0.082,
        0.066,  0.107,  0.195])

In [121]:
# 必要なライブラリのインポート
from sklearn.ensemble import RandomForestRegressor
# モデル構築、パラメータはデフォルト
forest = RandomForestRegressor()
forest.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [122]:
# 予測値を計算
y_train_pred = forest.predict(X_train)
y_test_pred = forest.predict(X_test)
# MSEの計算
from sklearn.metrics import mean_squared_error
print('MSE train : %.3f, test : %.3f' % (mean_squared_error(y_train, y_train_pred), mean_squared_error(y_test, y_test_pred)) )
# R^2の計算
from sklearn.metrics import r2_score
print('MSE train : %.3f, test : %.3f' % (r2_score(y_train, y_train_pred), r2_score(y_test, y_test_pred)) )

MSE train : 0.069, test : 0.430
MSE train : 0.891, test : 0.393


In [125]:
test= pd.read_csv("test.csv")
test.head()

id  fixed acidity  volatile acidity  citric acid  residual sugar  \
0   0            5.6              0.66         0.00             2.5   
1   1            7.9              0.54         0.34             2.5   
2   2            6.6              0.50         0.00             1.8   
3   3            6.3              0.47         0.00             1.4   
4   4           10.7              0.40         0.37             1.9   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.066                  7.0                  15.0  0.99256  3.52   
1      0.076                  8.0                  17.0  0.99235  3.20   
2      0.062                 21.0                  28.0  0.99352  3.44   
3      0.055                 27.0                  33.0  0.99220  3.45   
4      0.081                 17.0                  29.0  0.99674  3.12   

   sulphates  alcohol  
0       0.58     12.9  
1       0.72     13.1  
2       0.55     12.3  
3       0.48     12.3  
4       0.65     11.2

In [126]:
X_test_real=test.loc[:,["volatile acidity","citric acid","chlorides","total sulfur dioxide","density","sulphates","alcohol"]].values
X_test_real

array([[  0.66 ,   0.   ,   0.066, ...,   0.993,   0.58 ,  12.9  ],
       [  0.54 ,   0.34 ,   0.076, ...,   0.992,   0.72 ,  13.1  ],
       [  0.5  ,   0.   ,   0.062, ...,   0.994,   0.55 ,  12.3  ],
       ..., 
       [  0.51 ,   0.13 ,   0.076, ...,   0.996,   0.75 ,  11.   ],
       [  0.645,   0.12 ,   0.075, ...,   0.995,   0.71 ,  10.2  ],
       [  0.31 ,   0.47 ,   0.067, ...,   0.995,   0.66 ,  11.   ]])

In [127]:
predict = rfc.predict(X_test_real)

In [143]:
predict

array([6, 6, 6, 6, 5, 7, 6, 6, 6, 5, 6, 5, 5, 7, 6, 6, 6, 6, 6, 5, 5, 5, 6,
       6, 6, 6, 6, 6, 5, 7, 6, 7, 5, 5, 6, 6, 5, 7, 5, 6, 5, 7, 6, 7, 5, 5,
       6, 6, 7, 6, 6, 6, 6, 7, 6, 6, 6, 6, 7, 7, 7, 7, 6, 7, 5, 6, 7, 5, 7,
       6, 5, 6, 5, 7, 5, 5, 5, 5, 5, 6, 5, 5, 6, 7, 5, 6, 6, 6, 6, 6, 7, 6,
       5, 6, 7, 6, 6, 5, 6, 7, 7, 6, 6, 5, 7, 6, 5, 5, 5, 7, 5, 7, 6, 5, 5,
       6, 6, 6, 6, 5, 6, 5, 6, 7, 5, 5, 5, 5, 5, 7, 6, 6, 5, 5, 5, 6, 6, 5,
       6, 6, 6, 5, 4, 5, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 7, 5, 5, 6,
       6, 6, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 6, 6, 5, 7, 5, 7,
       7, 5, 5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 6, 6, 6, 6, 6,
       6, 6, 5, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 7, 5, 5,
       5, 6, 6, 5, 5, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 5, 6,
       5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5,
       5, 5, 5, 5, 6, 5, 5, 7, 6, 6, 7, 7, 6, 7, 6, 5, 7, 7, 5, 6, 6, 6, 7,
       5, 6,

In [142]:
np.savetxt("bar.csv", predict, delimiter=",")